ALTER TABLE IF EXISTS cvs
    ADD COLUMN IF NOT EXISTS cv_file_url VARCHAR(2048);

ALTER TABLE IF EXISTS cvs
    ALTER COLUMN full_name DROP NOT NULL;

ALTER TABLE IF EXISTS applicants
    ALTER COLUMN full_name DROP NOT NULL;

ALTER TABLE IF EXISTS recruiters
    ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(2048);
